//> using scala 3.3.6
//> using jvm 21
//> using dep "dev.zio::zio:2.1.22"
//> using dep "dev.zio::zio-cli:0.7.4"
//> using dep "io.circe::circe-core:0.14.10"
//> using dep "io.circe::circe-parser:0.14.10"
//> using dep "io.github.iltotore::iron:2.6.0"
//> using file "../core/src/main/scala"
//> using mainClass auth.cli.Main
